name: riv_auth_test
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  sizer: ^2.0.15
  flutter_riverpod: ^2.5.1
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  form_validators:
    path: packages/form_validators
  authentication_repository:
    path: packages/authentication_repository
  firebase_core: ^2.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true